### ISSUE TITLE
sever 如何启动

### ISSUE THREAD

**Issue by zerofront** [secreter/websocket_chat#2]
看了你的代码，受益匪浅，请问一下，你用的webpack模板，是有一个小型的express应用的。npm run dev之后是服务器启动监听的localhost：8080端口。
     但是你的聊天服务器server/index.js 监听的3000端口。
     在项目运行的时候，请问前端是如何和后端进行通信的？？为什么我没有 node server/index.js去启动聊天服务器，这个聊天室也能运行？？能否解释一下，谢谢

**Comment by zerofront** [comment]
为什么我本地 npm install &npm run dev 之后启动的localhost：8080 可以和微信上的用户交流的？？

**Comment by secreter** [comment]
我把这两个文件放在两个端口，是有两个原因的，一是因为它是一个消息处理中心，要24小时运行在后台，所有我单独给它一个进程和端口；另一方面就是，我当时不太会用express，只会最简单的处理一下，现在来看，其实同一个端口可以同时支持websocket和普通http请求的，这个你可以详细查一下。
至于你说的为什么你没有启动服务器也可以通信，是因为在代码里，我写的是wss://node.redream.cn/,其实这是我线上的服务器，所有你会看见可以和微信上的用户交流，你应该把这里换成你本地的服务地址。
