### ISSUE TITLE
一对一聊天

### ISSUE THREAD

**Issue by xiaozhu188** [secreter/websocket_chat#3]
请问怎么实现私聊呢~

**Comment by secreter** [comment]
```
io.on('connection', function (socket) {
  socket.emit('news', { hello: 'world' });
});
```
当有用户连接成功的时候，是会返回一个socket句柄的，你把所有句柄都用一个数组或对象存储起来，比如要实现id为111和222的用户单独通信，那么你收到111的消息后，不广播消息，而是根据222的id找到222的socket句柄，单独给222用户分发消息就行了。
可以看看官方文档https://socket.io/。
当然，如果实现不经过服务器的单独通信，可以用传输层协议TCP来实现。
