### ISSUE TITLE
可以把服务器端的代码放出来？

### ISSUE THREAD

**Issue by NancyZY** [secreter/websocket_chat#5]
因为不太熟悉这一块，想更好地理解这个Demo是如何与服务器进行的交互，谢谢了，🙏🙏

**Comment by secreter** [comment]
server文件夹下的就是服务器端代码

**Comment by NancyZY** [comment]
哦哦，看到了。但是我在本地运行nodejs 服务（在控制台运行node server/index.js ）时， 会出现重复发送的情况，但如果用你部署好的ws服务，不会有这个情况，这是为什么？
![image](https://cloud.githubusercontent.com/assets/9473445/25840889/49f3a64c-34d0-11e7-83da-b328322f96f6.png)
